services:
  postgres:
    image: postgres:9.4
    container_name: postgresdb
    environment:
      POSTGRES_DB: "transacaodb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      TZ: "GMT"
    volumes:
      - C:\dev\postgres\transacao:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    networks:
      - postgres-transacao

  pgadmin4:
    image: dpage/pgadmin4:4.10
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "secret"
    ports:
      - "8082:80"
volumes:
  postgres-volume:

networks:
  postgres-transacao: